### ISSUE TITLE
Config file in README cannot be accessed.

### ISSUE THREAD

**Issue by cylepsy** [Ruenzuo/gameshell-cross-compile#1]
I tried to check out the configuration file linked in README.md. However the link is no longer valid. Can you please update it?

> Simply follow the instructions on how to set up a toolchain from their Documentation page (pages 1-4). If you’re unsure about how to configure crosstool-ng, you can use my configuration available **here**. Some useful bits:

**Comment by UnsafePointer** [comment]
I changed my GitHub username, so the link broke. It's up to date now.
